Revert "Bump modello-maven-plugin from 1.10.0 to 1.11"
This reverts commit 5141a9ac35e95123446df0cb446f88e09f3d30de.
Error generating: There are more than one class as root element for this version 1.0.0.

Error: org.apache.maven.plugin.MojoExecutionException: Error generating: There are more than one class as root element for this version 1.0.0.